### ISSUE TITLE
Can't see left hand tracking in Sample Project.

### ISSUE THREAD

**Issue by Albith** [Srile/wle-peerjs-networking#8]
Hello, I've been running the example project in my Quest 2 (as host, using port forwarding) and PC (as client).
Seen from the PC,  the Head and Right arm track just fine.  But the left hand visible in my Quest 2 is not appearing  in the client.
I'm not sure why.  In the code for Peer Manager, I see that all transforms (Head, Left and Right hand) are being updated. 

[Animated Gif of the issue](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYjZiMzNiMDk4NGQwZjNkYWI3M2JkZTAxNzNlMDE1ZjlhYmE5ZmFlNCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/maT7e6sxde4amwcc3w/giphy.gif)

[Console readout in the client](https://cdn.discordapp.com/attachments/1101317096266280990/1101317096954155148/brave_8rv1SVB7pY.png)

**Comment by Srile** [comment]
Thank you for the issue. It has been fixed in the latest commit.

**Comment by Albith** [comment]
Thank you very much!
